public class lab6_diffie_hellman {
    public static void main(String args[]){
        
        int p=23, g=9, a=4, b=3;
        double x=0, y=0, ka=0, kb=0;
        System.out.println("Given public keys: p="+p+" g="+g);
        System.out.println("Selected private keys: user1= "+a+" user2= "+b);

        x = Math.pow(g, a)%p;
        y = Math.pow(g, b)%p;
        System.out.println("Keys generated by user1: "+x+", user2: "+y);

        ka = Math.pow(y, a)%p;
        kb = Math.pow(x, b)%p;
        System.out.println("After key exchange, secret key generated is: "+ka);
        System.out.println("Since ka= "+ka+ " and kb= "+kb+", it proves symmetric keys are generated");
    }
}
